// Импорт аудио
import audio1 from "../../assets/sound/fonk.mp3";
import audio2 from "../../assets/sound/granzh.mp3";
import audio3 from "../../assets/sound/acdc.mp3";

import poster1 from "../../assets/covers/111.jpg";
import poster2 from "../../assets/covers/222.jpg";
import poster3 from "../../assets/covers/333.jpg";

import { Track } from "./TrackList";

export const tracks: Track[] = [
  {
    id: 1,
    title: "Fonk",
    artist: "TMNV",
    poster: poster1,
    audioUrl: audio1,
    duration: "3:45",
  },
  {
    id: 2,
    title: "Vechno molodoy",
    artist: "Granzh",
    poster: poster2,
    audioUrl: audio2,
    duration: "4:20",
  },
  {
    id: 3,
    title: "Black in black",
    artist: "ACDC",
    poster: poster3,
    audioUrl: audio3,
    duration: "4:20",
  },
  {
    id: 4,
    title: "Fonk",
    artist: "TMNV",
    poster: poster1,
    audioUrl: audio1,
    duration: "3:45",
  },
  {
    id: 5,
    title: "Vechno molodoy",
    artist: "Granzh",
    poster: poster2,
    audioUrl: audio2,
    duration: "4:20",
  },
  {
    id: 6,
    title: "Black in black",
    artist: "ACDC",
    poster: poster3,
    audioUrl: audio3,
    duration: "4:20",
  },
  {
    id: 7,
    title: "Fonk",
    artist: "TMNV",
    poster: poster1,
    audioUrl: audio1,
    duration: "3:45",
  },
  {
    id: 8,
    title: "Vechno molodoy",
    artist: "Granzh",
    poster: poster2,
    audioUrl: audio2,
    duration: "4:20",
  },
  {
    id: 9,
    title: "Black in black",
    artist: "ACDC",
    poster: poster3,
    audioUrl: audio3,
    duration: "4:20",
  },
  {
    id: 10,
    title: "Fonk",
    artist: "TMNV",
    poster: poster1,
    audioUrl: audio1,
    duration: "3:45",
  },
  {
    id: 11,
    title: "Vechno molodoy",
    artist: "Granzh",
    poster: poster2,
    audioUrl: audio2,
    duration: "4:20",
  },
  {
    id: 12,
    title: "Black in black",
    artist: "ACDC",
    poster: poster3,
    audioUrl: audio3,
    duration: "4:20",
  },
  {
    id: 13,
    title: "Fonk",
    artist: "TMNV",
    poster: poster1,
    audioUrl: audio1,
    duration: "3:45",
  },
  {
    id: 14,
    title: "Vechno molodoy",
    artist: "Granzh",
    poster: poster2,
    audioUrl: audio2,
    duration: "4:20",
  },
  {
    id: 15,
    title: "Black in black",
    artist: "ACDC",
    poster: poster3,
    audioUrl: audio3,
    duration: "4:20",
  },
  {
    id: 16,
    title: "Fonk",
    artist: "TMNV",
    poster: poster1,
    audioUrl: audio1,
    duration: "3:45",
  },
  {
    id: 17,
    title: "Vechno molodoy",
    artist: "Granzh",
    poster: poster2,
    audioUrl: audio2,
    duration: "4:20",
  },
  {
    id: 18,
    title: "Black in black",
    artist: "ACDC",
    poster: poster3,
    audioUrl: audio3,
    duration: "4:20",
  },
  {
    id: 19,
    title: "Fonk",
    artist: "TMNV",
    poster: poster1,
    audioUrl: audio1,
    duration: "3:45",
  },
  {
    id: 20,
    title: "Vechno molodoy",
    artist: "Granzh",
    poster: poster2,
    audioUrl: audio2,
    duration: "4:20",
  },
  {
    id: 21,
    title: "Black in black",
    artist: "ACDC",
    poster: poster3,
    audioUrl: audio3,
    duration: "4:20",
  },
];
